spring.application.name=SpringbootMongodbCurdwithExcel

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Demodb

server.port=7777


